services:
  kenility-db:
    image: mongo:8.0.4-rc0-noble
    container_name: kenility-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - ./mongo-data:/data/db

