services:
  kenility-db:
    image: mongo:8.0.4-rc0-noble
    container_name: kenility-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
    volumes:
      - ./mongo-data:/data/db

  kenility-api:
    container_name: kenility-api
    build:
      context: ./
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/usr/src/app/src
    command: yarn start:dev
    environment:
      PORT: ${PORT}
      MONGO_DB_USERNAME: ${MONGO_DB_USERNAME}
      MONGO_DB_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - kenility-db

